name: 'Publish GitHub Action'
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ vars.GITHUB_ACTIONS == 'true' }}
    steps:
      - uses: actions/checkout@v5

      - name: Install esbuild
        run: npm i esbuild

      - uses: joshjohanning/publish-github-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_release_as_draft: true